events/api/urls.py
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register("category", views.CategoryViewset)
router.register("event", views.EventViewset)

events/urls.py
from django.urls import path
from . import views


app_name = "events"

urlpatterns = [
    path("hello", views.hello_world, name="hello_world"),
    # http://127.0.0.1:800/events/categories

    path("categories", views.list_categories, name="list_categories"),

    path("category/add", views.category_add, name="category_add"),
    path("category/<slug:slug>", views.category_detail, name="category_detail"),

    path("", views.EventListView.as_view(), name="list_events"),

    # http://127.0.0.1:8000/events/event/<slug-name>
    path("event/<slug:slug>", views.EventDetailView.as_view(), name="event_detail"),

    # http://127.0.0.1:8000/events/event/create/3
    path("event/create/<int:category_id>",
         views.EventCreateView.as_view(),
         name="event_create"),

    # http://127.0.0.1:8000/events/event/update/42
    path("event/update/<int:pk>",
         views.EventUpdateView.as_view(),
         name="event_update"),

    path("event/delete/<int:pk>",
         views.EventDeleteView.as_view(),
         name="event_delete")


]

user/urls.py
from django.urls import path
from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup")
]

events/models.py
from pyexpat import model
from tabnanny import verbose
from unicodedata import name
from wsgiref import validate
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.urls import reverse
from django.core.validators import MinLengthValidator, MaxLengthValidator
from .validators import datetime_future


User = get_user_model()

# Create your models here.


class DateMixin(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Category(DateMixin):
    name = models.CharField(max_length=100, unique=True)
    sub_title = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(
        null=True, blank=True, help_text="Die Beschreibung der Kategorie")
    slug = models.SlugField(unique=True)  # example.com/categories/abend-sport

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Categories"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("events:category_detail", kwargs={"slug": self.slug})

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Category._meta.fields]

    # def clean(self):
    #     print("Clean Model")
    #     return super().clean()

    def __str__(self):
        return self.name


class Event(DateMixin):

    class Group(models.IntegerChoices):
        BIG = 20
        MEDIUM = 10
        SMALL = 5
        MIN = 1

    class Meta:
        ordering = ["name"]
        permissions = (("can_say_hello", "Set event active"),)

    name = models.CharField(max_length=150, unique=True,
                            validators=[MinLengthValidator(3)])

    description = models.TextField(blank=True, null=True)
    #date = models.DateTimeField(validators=[datetime_future])
    date = models.DateTimeField()
    sub_title = models.CharField(max_length=200, null=True, blank=True)
    min_group = models.IntegerField(choices=Group.choices)
    is_active = models.BooleanField(default=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="events")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="events")
    slug = models.SlugField(unique=True)

    def get_absolute_url(self):
        return reverse("events:event_detail", kwargs={"slug": self.slug})

    def related_events(self):
        related_events = Event.objects.filter(
            min_group=self.min_group,
            category=self.category
        )
        return related_events.exclude(pk=self.id)

    def clean(self):
        # if self.sub_title != "egal":
        if self.category.name != "Sport":
            datetime_future(self.date)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Event, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

events/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Category, Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        exclude = "slug", "author", "category"
        widgets = {
            "date": forms.DateTimeInput(
                format=("%Y-%m-%d %H:%M"), attrs={"type": "datetime-local"}
            ),
        }


class EventUpdateForm(EventForm):
    class Meta(EventForm.Meta):
        exclude = "slug", "author"


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        # fields = "__all__"
        exclude = "slug",

        labels = {
            "sub_title": "Slogan"
        }

    message = forms.CharField(max_length=5)

    def clean_message(self):
        """clean_<feldname>"""
        print("Clean message")
        message = self.cleaned_data["message"]
        if isinstance(message, str) and message.startswith(("@", "?")):
            raise ValidationError("Diese Zeichen sind nicht legal")

        return message

    # def clean(self):
    #     """ Methode zum Vergleich zweier Formularfelder miteinander"""
    #     print("Form clean")

events/api/views.py
from rest_framework import viewsets, permissions, filters
from events import models
from .serializers import CategorySerializer, EventInlineSerializer
from rest_framework.authentication import TokenAuthentication


class CategoryViewset(viewsets.ModelViewSet):
    queryset = models.Category.objects.all()
    authentication_classes = (TokenAuthentication,)
    serializer_class = CategorySerializer
    # permission_classes = (permissions.IsAuthenticated,)
    filter_backends = [filters.OrderingFilter]
    ordering_fields = ["name"]


class EventViewset(viewsets.ModelViewSet):
    queryset = models.Event.objects.all()
    authentication_classes = (TokenAuthentication,)
    serializer_class = EventInlineSerializer
    filter_backends = [filters.OrderingFilter]
    ordering_fields = ["name", "date"]

events/views.py
from email import message
import logging
from pyexpat import model
from django.forms import ValidationError
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseForbidden
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Event, Category
from .forms import CategoryForm, EventForm, EventUpdateForm

logger = logging.getLogger("event_manager.events")

# Create your views here.


class EventDeleteView(LoginRequiredMixin, DeleteView):
    model = Event
    success_url = reverse_lazy('events:list_events')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user != self.get_object().author:
            return HttpResponseForbidden()
        return super().dispatch(request, *args, **kwargs)


class EventUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Event
    form_class = EventUpdateForm
    success_message = "Das Ändern des Events war erfolgreich."

    def form_valid(self, form):
        logger.debug("Es wurde ein Event upgedated")
        if form.instance.author != self.request.user:
            messages.info(self.request, "Hallo, das ist eine Testmessage!")
            raise ValidationError("Das ist nicht möglich")
        return super(EventUpdateView, self).form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user != self.get_object().author:
            return HttpResponseForbidden()
        return super().dispatch(request, *args, **kwargs)


class EventCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Event
    form_class = EventForm
    success_message = "Das Anlegen des Events war erfolgreich."

    def form_valid(self, form):
        """ Das wird vor dem Speichern in der DB aufgerufen"""
        form.instance.author = self.request.user
        form.instance.category = self.category
        return super(EventCreateView, self).form_valid(form)

    def get_initial(self):
        """ Das wird zuerst aufgerufen"""
        print("Request: ", self.request.__dict__)
        self.category = get_object_or_404(
            Category, pk=self.kwargs["category_id"]
        )


class EventDetailView(DetailView):
    model = Event
    # template_name = "events/event_detail.html"
    # event_detail.html
    # context name object


class EventListView(ListView):
    """http://127.0.0.1/events"""
    model = Event
    paginate_by = 6
    context_object_name = "events"

    def get_queryset(self):
        # Das würde im default passieren: queryset = Event.objects.all()
        queryset = Event.objects.select_related("category").all()
        if self.request.GET.get("category"):
            slug = self.request.GET.get("category")
            queryset = queryset.filter(category__slug=slug)
        return queryset


@permission_required("events.can_say_hello")
def hello_world(request):
    print(request.user)
    # print("REQUEST object", type(request), request.__dict__, request.user)
    return HttpResponse("Hallo Welt")


def list_categories(request):
    categories = Category.objects.all()
    return render(request,
                  "events/category_list.html",
                  {"categories": categories})


def category_detail(request, slug):
    category = get_object_or_404(Category, slug=slug)
    # category = Category.objects.get(slug=slug)
    return render(request,
                  "events/category_detail.html",
                  {"category": category})


def category_add(request):
    """http://127.0.0.1:8000/events/category/add"""
    if request.method == "POST":
        form = CategoryForm(request.POST or None)
        if form.is_valid():
            category = form.save(commit=False)
            category = form.save()
            # return redirect("events:list_categories")
            return redirect(category.get_absolute_url())
        else:
            print("Formular-Fehler: ", form.errors)
    else:
        form = CategoryForm()

    return render(request, "events/category_add.html", {"form": form})

events/templates/events/category_add.html
{% extends 'base.html' %}
{%load crispy_forms_tags %}
{% block title %}
Neue Kategorie hinzufügen
{% endblock %}

{% block head %}
Neue Kategorie hinzufügen
{% endblock %}

{% block content %}
<form method="POST">
{% csrf_token %}
{{form|crispy}}
<input type="submit" value="Formular absenden"/>
</form>

    
{% endblock %}

events/templates/events/category_detail.html
{% extends 'base.html' %}

{% block title %}
Kategorie-Detailseite
{% endblock %}

{% block head %}
Detailseite der Kategorie {{category.name}}
{% endblock %}

{% block content %}

<ul>
    {% for name, value in category.get_fields %}
      {% if value %}
        <li>{{ name }}: {{ value }}</li>
      {% endif %}
    {% endfor %}
</ul>
{% if user.is_authenticated %}
<p>
<a href="{% url 'events:event_create' category.pk %}"> neues Event in der Kategorie {{category.name}} anlegen </a>
</p>
{% endif %}

{% endblock %}

events/templates/events/category_list.html
{% extends 'base.html' %}

{% block title %}
Übersicht der Kategorien
{% endblock %}

{% block head %}
Übersicht der Kategorien
{% endblock %}

{% block content %}
    <ul>
    {% for cat in categories %}
    <li>
        <a href="{% url 'events:category_detail' cat.slug %}">{{cat.name}}</a>
        
    </a>
    {% endfor %}
{% endblock %}

events/templates/events/event_confirm_delete.html
{% extends 'base.html' %}
{%load crispy_forms_tags %}
{% block title %}
Event löschen
{% endblock %}

{% block head %}
Event {{object}} löschen?
{% endblock %}

{% block content %}
<form method="POST">
{% csrf_token %}

<input type="submit" value="Event wirklich löschen"/>

    
{% endblock %}

events/templates/events/event_detail.html
{% extends 'base.html' %}
{% load tz%}
{% block title %}
Detailseite des Events {{object.name}}
{% endblock %}

{% block head %}
Detailseite des Events {{object.name}}
{% endblock %}

{% block content %}
    
<ul class="list-group">
<h1> {{object.name}}  </h1>
<p> {{object.sub_title|lower}}</p>
<P>Findet statt am: {{object.date}} </p>
    {% localtime off %}
    <P> Findet statt am: {{object.date}}  (UTC) </p>
    {% endlocaltime %}
</ul>

{% comment %}
{% if user.is_authenticated and user == object.author %}
{% endcomment %}

<p>
<a href="{% url 'events:event_update' object.id %}"> Event editieren</a><br>
<a href="{% url 'events:event_delete' object.id %}"> Event löschen</a>
</p>
{% comment %}
{% endif %}
{% endcomment %}

{% if object.related_events.exists %}
<h3> Ähnliche Veranstaltungen  </h3>


{% for rel_event in object.related_events %}
<a href="{{rel_event.get_absolute_url}}">
<li class="list-group-item list-group-item-info">
{{rel_event.name}}
</li>
</a>
{% endfor%}

{% endif %}

{% include "../snippets/paginator.html" %}

{% endblock %}

events/templates/events/event_form.html
{% extends 'base.html' %}
{%load crispy_forms_tags %}
{% block title %}
Neues Event hinzufügen
{% endblock %}

{% block head %}
Neues Event hinzufügen
{% endblock %}

{% block content %}
<form method="POST">
{% csrf_token %}
{{form|crispy}}
<input type="submit" value="Event speichern"/>
</form>

    
{% endblock %}

events/templates/events/event_list.html
{% extends 'base.html' %}

{% block title %}
Übersicht der Events
{% endblock %}

{% block head %}
Übersicht der Events
{% endblock %}

{% block content %}
    
<ul class="list-group">

    {% for event in events %}
    <a href="{{event.get_absolute_url}}">
    <li class="list-group-item list-group-item-info">
        
        {{event.name}} <span class="badge badge-primary badge-pill">{{event.category.name}}</span>
        <span class="badge badge-secondary badge-pill">{{event.author}}</span>
    </li>
</a>
    {% endfor %}
</ul>

{% include "../snippets/paginator.html" %}

{% endblock %}